// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgkM6aUXaY5C4yn6C-aH4sFrh_rLhVcrI',
    appId: '1:393639064312:web:009fcadd31f395489c410d',
    messagingSenderId: '393639064312',
    projectId: 'krimp-43829',
    authDomain: 'krimp-43829.firebaseapp.com',
    storageBucket: 'krimp-43829.appspot.com',
    measurementId: 'G-58XN9V8N9Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiqDQAf2-lbFacdzdKfsKUyta6_a1RSi4',
    appId: '1:393639064312:android:931b1a962fb0c1c19c410d',
    messagingSenderId: '393639064312',
    projectId: 'krimp-43829',
    storageBucket: 'krimp-43829.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWgrm_fmXsnoZ41th4Njemeq5Gg9ehBck',
    appId: '1:393639064312:ios:f3b9fe2a9b1bf6559c410d',
    messagingSenderId: '393639064312',
    projectId: 'krimp-43829',
    storageBucket: 'krimp-43829.appspot.com',
    iosClientId: '393639064312-flkidt432jr23iea17s4kkin4jlrkgnk.apps.googleusercontent.com',
    iosBundleId: 'com.dtronics.krimp',
  );
}
